// Generated by tools/gen_tuning.py; edit the list there, not this file.
class MemeTuningConfig extends Object config(Game);

// Reads [MemeMod.MemeTuningConfig] from MemeMod.ini. MemeTuning copies these on the server.

var config float MCommitFraction;
var config float MServerCommitSlack;
var config float MChainWindupScale;
var config float MRiposteWindupScale;
var config float MRiposteWindow;
var config float MParryWindow;
var config float MContactRecoveryScale;
var config float MKickWhiffRecovery;
var config float MRecoveryParryFraction;
var config float MGuardMoveScale;
var config float MGuardDropTime;
var config float MMissedParryRecovery;
var config float MFeintTime;
var config float MFeintCost;
var config float MStaggerHit;
var config float MStaggerKick;
var config float MStaggerBreak;
var config float MStaggerParryFraction;
var config float MWindupTurn;
var config float MStrikeTurn;
var config float MStabStrikeTurn;
var config float MHoldMax;
var config float MHoldCost;
var config bool bMHoldOnAttackButton;
var config float MemeBladeRadius;
var config float MemeClashRadius;
var config float MemeProxyDelay;
var config float MemeMaxRewind;
var config float MemeMaxHold;
var config float MemeMaxOneWay;
var config float MemeInitiativeWindow;
var config float MemeWorldMinProgress;
var config float MemeKickActiveAt;
var config float MemeParryCone;
var config float MemeGuardCone;
var config float MemeShieldCone;
var config float MemeGuardCostLight;
var config float MemeGuardCostMedium;
var config float MemeGuardCostHeavy;
var config float MemeShieldGuardScale;
var config float MemeKickGuardCost;
var config float MemePerfectParryAttackerCost;
var config float MemeParriedRecoil;
var config float MemeBlockedRecoil;
var config float MemeClashRecoil;
var config float MemeWorldRecoil;
var config float MemePostureRegen;
var config float MemePostureRegenDelay;
var config float MemeHitStopRate;
var config float MemeHitStopTime;
var config float MemeLowPostureCue;
var config float MemeCueTime;
var config float MemeCueScale;
var config float MReactSlow;
var config float MReactFast;
var config float MErrSlow;
var config float MErrFast;
var config float MContactLead;
var config float MThreatRange;
var config float MLowPosture;
var config float MAggression;
var config float MAttackGapSlow;
var config float MAttackGapFast;
var config float MPunishSlow;
var config float MPunishFast;
var config float MReachSlack;

DefaultProperties
{
`include(MemeMod/Include/MemeWeaponTuning.uci)
`include(MemeMod/Include/MemePawnTuning.uci)
`include(MemeMod/Include/MemeAIDefaults.uci)
}
