// Generated by tools/gen_tuning.py; edit the list there, not this file.
class MemeTuningConfig extends Object config(Game);

// Optional overrides from [MemeMod.MemeTuningConfig] in MemeMod.ini, one "Tune=<name> <value>" line each.
// UE3 ignores DefaultProperties for config vars, so the defaults live in MemeTuning instead.

var config array<string> Tune;
