// Generated by tools/gen_tuning.py; edit the list there, not this file.
class MemeTuning extends ReplicationInfo;

// Live tunables. The server applies MemeTuningConfig's ini overrides and replicates the result, so clients
// predict with the server's values. Admins change them with MemeTune; Version tells consumers to re-copy.

var int Version;
var float MCommitFraction;
var float MServerCommitSlack;
var float MChainWindupScale;
var float MRiposteWindupScale;
var float MRiposteWindow;
var float MParryWindow;
var float MContactRecoveryScale;
var float MKickWhiffRecovery;
var float MRecoveryParryFraction;
var float MGuardMoveScale;
var float MGuardDropTime;
var float MMissedParryRecovery;
var float MFeintTime;
var float MFeintCost;
var float MStaggerHit;
var float MStaggerKick;
var float MStaggerBreak;
var float MStaggerParryFraction;
var float MWindupTurn;
var float MStrikeTurn;
var float MStabStrikeTurn;
var float MHoldMax;
var float MHoldCost;
var bool bMHoldOnAttackButton;
var float MemeBladeRadius;
var float MemeClashRadius;
var float MemeProxyDelay;
var float MemeMaxRewind;
var float MemeMaxHold;
var float MemeMaxOneWay;
var float MemeInitiativeWindow;
var float MemeWorldMinProgress;
var float MemeKickActiveAt;
var float MemeParryCone;
var float MemeGuardCone;
var float MemeShieldCone;
var float MemeGuardCostLight;
var float MemeGuardCostMedium;
var float MemeGuardCostHeavy;
var float MemeShieldGuardScale;
var float MemeKickGuardCost;
var float MemePerfectParryAttackerCost;
var float MemeParriedRecoil;
var float MemeBlockedRecoil;
var float MemeClashRecoil;
var float MemeWorldRecoil;
var float MemePostureRegen;
var float MemePostureRegenDelay;
var float MemeHitStopRate;
var float MemeHitStopTime;
var float MemeLowPostureCue;
var float MemeCueTime;
var float MemeCueScale;
var float MReactSlow;
var float MReactFast;
var float MErrSlow;
var float MErrFast;
var float MContactLead;
var float MThreatRange;
var float MLowPosture;
var float MAggression;
var float MAttackGapSlow;
var float MAttackGapFast;
var float MPunishSlow;
var float MPunishFast;
var float MReachSlack;

replication
{
	if (bNetDirty)
		Version,
		MCommitFraction,
		MServerCommitSlack,
		MChainWindupScale,
		MRiposteWindupScale,
		MRiposteWindow,
		MParryWindow,
		MContactRecoveryScale,
		MKickWhiffRecovery,
		MRecoveryParryFraction,
		MGuardMoveScale,
		MGuardDropTime,
		MMissedParryRecovery,
		MFeintTime,
		MFeintCost,
		MStaggerHit,
		MStaggerKick,
		MStaggerBreak,
		MStaggerParryFraction,
		MWindupTurn,
		MStrikeTurn,
		MStabStrikeTurn,
		MHoldMax,
		MHoldCost,
		bMHoldOnAttackButton,
		MemeBladeRadius,
		MemeClashRadius,
		MemeProxyDelay,
		MemeMaxRewind,
		MemeMaxHold,
		MemeMaxOneWay,
		MemeInitiativeWindow,
		MemeWorldMinProgress,
		MemeKickActiveAt,
		MemeParryCone,
		MemeGuardCone,
		MemeShieldCone,
		MemeGuardCostLight,
		MemeGuardCostMedium,
		MemeGuardCostHeavy,
		MemeShieldGuardScale,
		MemeKickGuardCost,
		MemePerfectParryAttackerCost,
		MemeParriedRecoil,
		MemeBlockedRecoil,
		MemeClashRecoil,
		MemeWorldRecoil,
		MemePostureRegen,
		MemePostureRegenDelay,
		MemeHitStopRate,
		MemeHitStopTime,
		MemeLowPostureCue,
		MemeCueTime,
		MemeCueScale,
		MReactSlow,
		MReactFast,
		MErrSlow,
		MErrFast,
		MContactLead,
		MThreatRange,
		MLowPosture,
		MAggression,
		MAttackGapSlow,
		MAttackGapFast,
		MPunishSlow,
		MPunishFast,
		MReachSlack;
}

// Server spawns the single instance on first use; clients wait for it to replicate.
static function MemeTuning Get(WorldInfo WI)
{
	local MemeTuning MT;

	if (WI == none)
		return none;
	foreach WI.DynamicActors(class'MemeTuning', MT)
		return MT;
	if (WI.NetMode != NM_Client)
	{
		MT = WI.Spawn(class'MemeTuning');
		if (MT != none)
			MT.LoadConfigValues();
	}
	return MT;
}

// Applies "Tune=<name> <value>" lines from MemeMod.ini on top of the defaults below.
function LoadConfigValues()
{
	local string L;
	local int i, Sp;

	for (i = 0; i < class'MemeTuningConfig'.default.Tune.Length; i++)
	{
		L = class'MemeTuningConfig'.default.Tune[i];
		Sp = InStr(L, " ");
		if (Sp > 0)
			SetByName(Left(L, Sp), Mid(L, Sp + 1));
	}
	Version = 1;
	bForceNetUpdate = true;
}

function bool SetByName(string N, string S)
{
	local float V;

	V = float(S);
	if (V == 0.f && !(S ~= "0" || S ~= "0.0" || S ~= "false" || S ~= "true"))
		return false;
	if (N ~= "MCommitFraction") { MCommitFraction = V; Version++; return true; }
	if (N ~= "MServerCommitSlack") { MServerCommitSlack = V; Version++; return true; }
	if (N ~= "MChainWindupScale") { MChainWindupScale = V; Version++; return true; }
	if (N ~= "MRiposteWindupScale") { MRiposteWindupScale = V; Version++; return true; }
	if (N ~= "MRiposteWindow") { MRiposteWindow = V; Version++; return true; }
	if (N ~= "MParryWindow") { MParryWindow = V; Version++; return true; }
	if (N ~= "MContactRecoveryScale") { MContactRecoveryScale = V; Version++; return true; }
	if (N ~= "MKickWhiffRecovery") { MKickWhiffRecovery = V; Version++; return true; }
	if (N ~= "MRecoveryParryFraction") { MRecoveryParryFraction = V; Version++; return true; }
	if (N ~= "MGuardMoveScale") { MGuardMoveScale = V; Version++; return true; }
	if (N ~= "MGuardDropTime") { MGuardDropTime = V; Version++; return true; }
	if (N ~= "MMissedParryRecovery") { MMissedParryRecovery = V; Version++; return true; }
	if (N ~= "MFeintTime") { MFeintTime = V; Version++; return true; }
	if (N ~= "MFeintCost") { MFeintCost = V; Version++; return true; }
	if (N ~= "MStaggerHit") { MStaggerHit = V; Version++; return true; }
	if (N ~= "MStaggerKick") { MStaggerKick = V; Version++; return true; }
	if (N ~= "MStaggerBreak") { MStaggerBreak = V; Version++; return true; }
	if (N ~= "MStaggerParryFraction") { MStaggerParryFraction = V; Version++; return true; }
	if (N ~= "MWindupTurn") { MWindupTurn = V; Version++; return true; }
	if (N ~= "MStrikeTurn") { MStrikeTurn = V; Version++; return true; }
	if (N ~= "MStabStrikeTurn") { MStabStrikeTurn = V; Version++; return true; }
	if (N ~= "MHoldMax") { MHoldMax = V; Version++; return true; }
	if (N ~= "MHoldCost") { MHoldCost = V; Version++; return true; }
	if (N ~= "bMHoldOnAttackButton") { bMHoldOnAttackButton = (V != 0.f || S ~= "true"); Version++; return true; }
	if (N ~= "MemeBladeRadius") { MemeBladeRadius = V; Version++; return true; }
	if (N ~= "MemeClashRadius") { MemeClashRadius = V; Version++; return true; }
	if (N ~= "MemeProxyDelay") { MemeProxyDelay = V; Version++; return true; }
	if (N ~= "MemeMaxRewind") { MemeMaxRewind = V; Version++; return true; }
	if (N ~= "MemeMaxHold") { MemeMaxHold = V; Version++; return true; }
	if (N ~= "MemeMaxOneWay") { MemeMaxOneWay = V; Version++; return true; }
	if (N ~= "MemeInitiativeWindow") { MemeInitiativeWindow = V; Version++; return true; }
	if (N ~= "MemeWorldMinProgress") { MemeWorldMinProgress = V; Version++; return true; }
	if (N ~= "MemeKickActiveAt") { MemeKickActiveAt = V; Version++; return true; }
	if (N ~= "MemeParryCone") { MemeParryCone = V; Version++; return true; }
	if (N ~= "MemeGuardCone") { MemeGuardCone = V; Version++; return true; }
	if (N ~= "MemeShieldCone") { MemeShieldCone = V; Version++; return true; }
	if (N ~= "MemeGuardCostLight") { MemeGuardCostLight = V; Version++; return true; }
	if (N ~= "MemeGuardCostMedium") { MemeGuardCostMedium = V; Version++; return true; }
	if (N ~= "MemeGuardCostHeavy") { MemeGuardCostHeavy = V; Version++; return true; }
	if (N ~= "MemeShieldGuardScale") { MemeShieldGuardScale = V; Version++; return true; }
	if (N ~= "MemeKickGuardCost") { MemeKickGuardCost = V; Version++; return true; }
	if (N ~= "MemePerfectParryAttackerCost") { MemePerfectParryAttackerCost = V; Version++; return true; }
	if (N ~= "MemeParriedRecoil") { MemeParriedRecoil = V; Version++; return true; }
	if (N ~= "MemeBlockedRecoil") { MemeBlockedRecoil = V; Version++; return true; }
	if (N ~= "MemeClashRecoil") { MemeClashRecoil = V; Version++; return true; }
	if (N ~= "MemeWorldRecoil") { MemeWorldRecoil = V; Version++; return true; }
	if (N ~= "MemePostureRegen") { MemePostureRegen = V; Version++; return true; }
	if (N ~= "MemePostureRegenDelay") { MemePostureRegenDelay = V; Version++; return true; }
	if (N ~= "MemeHitStopRate") { MemeHitStopRate = V; Version++; return true; }
	if (N ~= "MemeHitStopTime") { MemeHitStopTime = V; Version++; return true; }
	if (N ~= "MemeLowPostureCue") { MemeLowPostureCue = V; Version++; return true; }
	if (N ~= "MemeCueTime") { MemeCueTime = V; Version++; return true; }
	if (N ~= "MemeCueScale") { MemeCueScale = V; Version++; return true; }
	if (N ~= "MReactSlow") { MReactSlow = V; Version++; return true; }
	if (N ~= "MReactFast") { MReactFast = V; Version++; return true; }
	if (N ~= "MErrSlow") { MErrSlow = V; Version++; return true; }
	if (N ~= "MErrFast") { MErrFast = V; Version++; return true; }
	if (N ~= "MContactLead") { MContactLead = V; Version++; return true; }
	if (N ~= "MThreatRange") { MThreatRange = V; Version++; return true; }
	if (N ~= "MLowPosture") { MLowPosture = V; Version++; return true; }
	if (N ~= "MAggression") { MAggression = V; Version++; return true; }
	if (N ~= "MAttackGapSlow") { MAttackGapSlow = V; Version++; return true; }
	if (N ~= "MAttackGapFast") { MAttackGapFast = V; Version++; return true; }
	if (N ~= "MPunishSlow") { MPunishSlow = V; Version++; return true; }
	if (N ~= "MPunishFast") { MPunishFast = V; Version++; return true; }
	if (N ~= "MReachSlack") { MReachSlack = V; Version++; return true; }
	return false;
}

function string GetByName(string N)
{
	if (N ~= "MCommitFraction") return string(MCommitFraction);
	if (N ~= "MServerCommitSlack") return string(MServerCommitSlack);
	if (N ~= "MChainWindupScale") return string(MChainWindupScale);
	if (N ~= "MRiposteWindupScale") return string(MRiposteWindupScale);
	if (N ~= "MRiposteWindow") return string(MRiposteWindow);
	if (N ~= "MParryWindow") return string(MParryWindow);
	if (N ~= "MContactRecoveryScale") return string(MContactRecoveryScale);
	if (N ~= "MKickWhiffRecovery") return string(MKickWhiffRecovery);
	if (N ~= "MRecoveryParryFraction") return string(MRecoveryParryFraction);
	if (N ~= "MGuardMoveScale") return string(MGuardMoveScale);
	if (N ~= "MGuardDropTime") return string(MGuardDropTime);
	if (N ~= "MMissedParryRecovery") return string(MMissedParryRecovery);
	if (N ~= "MFeintTime") return string(MFeintTime);
	if (N ~= "MFeintCost") return string(MFeintCost);
	if (N ~= "MStaggerHit") return string(MStaggerHit);
	if (N ~= "MStaggerKick") return string(MStaggerKick);
	if (N ~= "MStaggerBreak") return string(MStaggerBreak);
	if (N ~= "MStaggerParryFraction") return string(MStaggerParryFraction);
	if (N ~= "MWindupTurn") return string(MWindupTurn);
	if (N ~= "MStrikeTurn") return string(MStrikeTurn);
	if (N ~= "MStabStrikeTurn") return string(MStabStrikeTurn);
	if (N ~= "MHoldMax") return string(MHoldMax);
	if (N ~= "MHoldCost") return string(MHoldCost);
	if (N ~= "bMHoldOnAttackButton") return string(bMHoldOnAttackButton);
	if (N ~= "MemeBladeRadius") return string(MemeBladeRadius);
	if (N ~= "MemeClashRadius") return string(MemeClashRadius);
	if (N ~= "MemeProxyDelay") return string(MemeProxyDelay);
	if (N ~= "MemeMaxRewind") return string(MemeMaxRewind);
	if (N ~= "MemeMaxHold") return string(MemeMaxHold);
	if (N ~= "MemeMaxOneWay") return string(MemeMaxOneWay);
	if (N ~= "MemeInitiativeWindow") return string(MemeInitiativeWindow);
	if (N ~= "MemeWorldMinProgress") return string(MemeWorldMinProgress);
	if (N ~= "MemeKickActiveAt") return string(MemeKickActiveAt);
	if (N ~= "MemeParryCone") return string(MemeParryCone);
	if (N ~= "MemeGuardCone") return string(MemeGuardCone);
	if (N ~= "MemeShieldCone") return string(MemeShieldCone);
	if (N ~= "MemeGuardCostLight") return string(MemeGuardCostLight);
	if (N ~= "MemeGuardCostMedium") return string(MemeGuardCostMedium);
	if (N ~= "MemeGuardCostHeavy") return string(MemeGuardCostHeavy);
	if (N ~= "MemeShieldGuardScale") return string(MemeShieldGuardScale);
	if (N ~= "MemeKickGuardCost") return string(MemeKickGuardCost);
	if (N ~= "MemePerfectParryAttackerCost") return string(MemePerfectParryAttackerCost);
	if (N ~= "MemeParriedRecoil") return string(MemeParriedRecoil);
	if (N ~= "MemeBlockedRecoil") return string(MemeBlockedRecoil);
	if (N ~= "MemeClashRecoil") return string(MemeClashRecoil);
	if (N ~= "MemeWorldRecoil") return string(MemeWorldRecoil);
	if (N ~= "MemePostureRegen") return string(MemePostureRegen);
	if (N ~= "MemePostureRegenDelay") return string(MemePostureRegenDelay);
	if (N ~= "MemeHitStopRate") return string(MemeHitStopRate);
	if (N ~= "MemeHitStopTime") return string(MemeHitStopTime);
	if (N ~= "MemeLowPostureCue") return string(MemeLowPostureCue);
	if (N ~= "MemeCueTime") return string(MemeCueTime);
	if (N ~= "MemeCueScale") return string(MemeCueScale);
	if (N ~= "MReactSlow") return string(MReactSlow);
	if (N ~= "MReactFast") return string(MReactFast);
	if (N ~= "MErrSlow") return string(MErrSlow);
	if (N ~= "MErrFast") return string(MErrFast);
	if (N ~= "MContactLead") return string(MContactLead);
	if (N ~= "MThreatRange") return string(MThreatRange);
	if (N ~= "MLowPosture") return string(MLowPosture);
	if (N ~= "MAggression") return string(MAggression);
	if (N ~= "MAttackGapSlow") return string(MAttackGapSlow);
	if (N ~= "MAttackGapFast") return string(MAttackGapFast);
	if (N ~= "MPunishSlow") return string(MPunishSlow);
	if (N ~= "MPunishFast") return string(MPunishFast);
	if (N ~= "MReachSlack") return string(MReachSlack);
	return "";
}

function string NameAt(int i)
{
	switch (i)
	{
		case 0: return "MCommitFraction";
		case 1: return "MServerCommitSlack";
		case 2: return "MChainWindupScale";
		case 3: return "MRiposteWindupScale";
		case 4: return "MRiposteWindow";
		case 5: return "MParryWindow";
		case 6: return "MContactRecoveryScale";
		case 7: return "MKickWhiffRecovery";
		case 8: return "MRecoveryParryFraction";
		case 9: return "MGuardMoveScale";
		case 10: return "MGuardDropTime";
		case 11: return "MMissedParryRecovery";
		case 12: return "MFeintTime";
		case 13: return "MFeintCost";
		case 14: return "MStaggerHit";
		case 15: return "MStaggerKick";
		case 16: return "MStaggerBreak";
		case 17: return "MStaggerParryFraction";
		case 18: return "MWindupTurn";
		case 19: return "MStrikeTurn";
		case 20: return "MStabStrikeTurn";
		case 21: return "MHoldMax";
		case 22: return "MHoldCost";
		case 23: return "bMHoldOnAttackButton";
		case 24: return "MemeBladeRadius";
		case 25: return "MemeClashRadius";
		case 26: return "MemeProxyDelay";
		case 27: return "MemeMaxRewind";
		case 28: return "MemeMaxHold";
		case 29: return "MemeMaxOneWay";
		case 30: return "MemeInitiativeWindow";
		case 31: return "MemeWorldMinProgress";
		case 32: return "MemeKickActiveAt";
		case 33: return "MemeParryCone";
		case 34: return "MemeGuardCone";
		case 35: return "MemeShieldCone";
		case 36: return "MemeGuardCostLight";
		case 37: return "MemeGuardCostMedium";
		case 38: return "MemeGuardCostHeavy";
		case 39: return "MemeShieldGuardScale";
		case 40: return "MemeKickGuardCost";
		case 41: return "MemePerfectParryAttackerCost";
		case 42: return "MemeParriedRecoil";
		case 43: return "MemeBlockedRecoil";
		case 44: return "MemeClashRecoil";
		case 45: return "MemeWorldRecoil";
		case 46: return "MemePostureRegen";
		case 47: return "MemePostureRegenDelay";
		case 48: return "MemeHitStopRate";
		case 49: return "MemeHitStopTime";
		case 50: return "MemeLowPostureCue";
		case 51: return "MemeCueTime";
		case 52: return "MemeCueScale";
		case 53: return "MReactSlow";
		case 54: return "MReactFast";
		case 55: return "MErrSlow";
		case 56: return "MErrFast";
		case 57: return "MContactLead";
		case 58: return "MThreatRange";
		case 59: return "MLowPosture";
		case 60: return "MAggression";
		case 61: return "MAttackGapSlow";
		case 62: return "MAttackGapFast";
		case 63: return "MPunishSlow";
		case 64: return "MPunishFast";
		case 65: return "MReachSlack";
	}
	return "";
}

DefaultProperties
{
`include(MemeMod/Include/MemeWeaponTuning.uci)
`include(MemeMod/Include/MemePawnTuning.uci)
`include(MemeMod/Include/MemeAIDefaults.uci)
	bAlwaysRelevant=true
}
